# Use root/example as user/password credentials
version: '2.1'

services:
  db:
    container_name: sqltools_mysql
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    ports:
      - 3307:3306

  db_xprotocol:
    container_name: sqltools_mysql_xprotocol
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    ports:
      - 3308:3306
      - 33080:33060
